require("dotenv").config();
const {Client} = require('pg');

const client = new Client({
  host: process.env.DB_HOST,
  port: process.env.DB_PORT,
  user: process.env.DB_USER,
  database: process.env.DB_NAME,
  password: process.env.DB_PASSWORD
});

client.connect((err) => {
  if (err) {
    console.error('connect error: ', err.stack)
  } else {
    console.log('connected!')
  }
})

const setNewSequenceVal = (name) => {
  var tableName = name + 's';
  var seqName = name + '_seq';
  return client.query(`SELECT count(*) FROM ${tableName};`)
    .then((res) => {
      console.log(`Count of ${tableName} table: ${res.rows[0].count}`)
      return client.query(`SELECT setval('${seqName}', '${res.rows[0].count}');`)
    })
    .catch(err => console.error('setNewSequenceVal error: ', err.stack));
}

console.log('Start loading data!')
client
  .query(`COPY reviews(id, product_id, rating, date, summary, body, recommended, reported, reviewer_name, reviewer_email, response, helpfulness) FROM '/Users/huantran/documents/Hack_Reactor/review-csv/reviews.csv' DELIMITER ',' NULL AS 'null' CSV HEADER;`)
  .then((res) => {
    console.log(`Reviews data successfully loaded to reviews table with ${res.rowCount} rows`);
    // Create index for reviews table on product_id column, help boost the query speed
    return client.query(`CREATE INDEX IF NOT EXISTS review_product_id_index ON reviews(product_id);`)
  })
  .then(() => {
    console.log('Index on product_id column in reviews table successfully successfully')
    // Update new start value for review sequence
    setNewSequenceVal('review');
  })
  .then(() => {
    console.log('Review sequence successfully updated');
    // Convert date from unix time to ISO time
    return client.query(`ALTER TABLE reviews ALTER COLUMN date SET DATA TYPE TIMESTAMP WITH TIME ZONE USING to_timestamp(date/1000) DEFAULT now();`)
  })
  .then(() => {
    console.log('Date comlumn successfully converted');
    // Copy data from reviews_photos.csv to photos table
    return client.query(`COPY photos(id, review_id, url) FROM '/Users/huantran/documents/Hack_Reactor/review-csv/reviews_photos.csv' DELIMITER ',' CSV HEADER;`)
  })
  .then((res) => {
    console.log(`Photos data successfully loaded to photos table  with ${res.rowCount} rows`);
    // Create index for photos table on review_id column, help boost the query speed
    return client.query(`CREATE INDEX IF NOT EXISTS photo_review_id_index ON photos(review_id);`)
  })
  .then(() => {
    console.log('Index on review_id column in photos table successfully successfully')
    // Update new start value for photos sequence
    setNewSequenceVal('photo');
  })
  .then(() => {
    console.log('Photo sequence successfully updated');
    // Create temporaty table for characteristics data
    return client.query(`CREATE TABLE IF NOT EXISTS temp_char_1 (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
      product_id BIGINT NOT NULL,
      type VARCHAR(20));`)
  })
  .then(() => {
    console.log('temp_char_1 table successfully created')
    // Copy data from characteristics.csv to temp_char_1 table
    return client.query(`COPY temp_char_1(id, product_id, type) FROM '/Users/huantran/documents/Hack_Reactor/review-csv/characteristics.csv' DELIMITER ',' CSV HEADER;`)
  })
  .then((res) => {
    console.log(`Charateristics data successfully loaded to temp_char_1 table  with ${res.rowCount} rows`);
    // Create temporaty table for characteristic_reviews data
    return client.query(`CREATE TABLE IF NOT EXISTS temp_char_2 (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
      char_id BIGINT NOT NULL,
      value INT NOT NULL,
      review_id BIGINT NOT NULL,
      CONSTRAINT fk_review
        FOREIGN KEY (review_id)
          REFERENCES reviews(id));`)
  })
  .then(() => {
    console.log('temp_char_2 table successfully created')
    // Copy data from characteristic_reviews.csv to temp_char_2 table
    return client.query(`COPY temp_char_2(id, char_id, review_id, value) FROM '/Users/huantran/documents/Hack_Reactor/review-csv/characteristic_reviews.csv' DELIMITER ',' CSV HEADER;`)
  })
  .then((res) => {
    console.log(`Charateristic reviews data successfully loaded to temp_char_2 table with ${res.rowCount} rows`);
    // Join temp_char_1 and temp_char_2 together and insert data to characteristics table
    return client.query(`INSERT INTO "characteristics" SELECT temp_char_2.id, type, value, review_id, product_id FROM temp_char_2 LEFT JOIN temp_char_1 ON temp_char_1.id = char_id;
    `)
  })
  .then((res) => {
    console.log(`Characteristics data successfully joined and loaded to characteristics table with ${res.rowCount} rows`);
    // Create index for characteristics table on product_id column, help boost the query speed
    return client.query(`CREATE INDEX IF NOT EXISTS char_product_id_index ON characteristics(product_id);`)
  })
  .then(() => {
    console.log('Index on product_id column in characteristics table successfully successfully')
    // Update new start value for characteristic sequence
    setNewSequenceVal('characteristic');
  })
  .then(() => {
    console.log('Characteristic sequence successfully updated');
    // Drop temp_char_1 table
    return client.query(`DROP TABLE temp_char_1`);
  })
  .then(() => {
    console.log('temp_char_1 table successfully dropped');
    // Drop temp_char_2 table
    return client.query(`DROP TABLE temp_char_2`);
  })
  .then(() => {
    console.log('temp_char_2 table successfully dropped');
    return client.end();
  })
  .then(() => console.log('Loadding process done!!!'))
  .catch(err => {
    console.log(err.message)
  })