const {Pool} = require('pg');

const pool = new Pool({
  host: 'localhost',
  port: 5432,
  user: 'huantran',
  database: 'sdc',
  password: ''
});

module.exports = pool;

// Create reviews table
pool
  .query(`CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    summary VARCHAR(255),
    body TEXT NOT NULL,
    rating INT NOT NULL,
    date BIGINT NOT NULL,
    reviewer_name VARCHAR(100) NOT NULL,
    reviewer_email VARCHAR(150) NOT NULL,
    recommended BOOLEAN NOT NULL,
    helpfulness INT NOT NULL DEFAULT 0,
    reported BOOLEAN NOT NULL DEFAULT false,
    response TEXT,
    product_id BIGINT NOT NULL);`)
  .then(() => {
    console.log('reviews table successfully created')
    // Create review sequence
    return pool.query(`CREATE SEQUENCE IF NOT EXISTS review_seq START 1 INCREMENT 1 OWNED BY reviews.id`)
  })
  .then(() => {
    console.log('review sequence successfully created')
    // Create photos table
    return pool.query(`CREATE TABLE IF NOT EXISTS photos (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
      url VARCHAR(255),
      review_id BIGINT NOT NULL,
      CONSTRAINT fk_review
        FOREIGN KEY (review_id)
          REFERENCES reviews(id));`)
  })
  .then(() => {
    console.log('photos table successfully created')
    // Create photo sequence
    return pool.query(`CREATE SEQUENCE IF NOT EXISTS photo_seq START 1 INCREMENT 1 OWNED BY photos.id`)
  })
  .then(() => {
    console.log('photo sequence successfully created')
    // Create characteristics table
    return pool.query(`CREATE TABLE IF NOT EXISTS characteristics (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
      type VARCHAR(100),
      value INT NOT NULL,
      review_id BIGINT NOT NULL,
      product_id BIGINT NOT NULL,
      CONSTRAINT fk_review
        FOREIGN KEY (review_id)
          REFERENCES reviews(id));`)
  })
  .then(() => {
    console.log('characteristics table successfully created')
    // Create characteristic sequence
    return pool.query(`CREATE SEQUENCE IF NOT EXISTS characteristic_seq START 1 INCREMENT 1 OWNED BY characteristics.id`)
  })
  .then(() => {
    console.log('characteristic sequence successfully created')
    console.log('Done creating tables and sequences!!!')
  })
  .catch(err => {
    console.log(err.message)
  })

